-- Create database:
CREATE DATABASE IF NOT EXISTS `PARSER` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `parser`;


-- Create tables:

DROP TABLE IF EXISTS `PS_BLOCK`;
CREATE TABLE `PS_BLOCK` (
  `ID_BLOCK` bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `DS_COMMENT` varchar(120) NOT NULL,
  `DS_IP` varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PS_REQUEST`;
CREATE TABLE `PS_REQUEST` (
  `ID_REQUEST` bigint UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `DT_DATE` datetime NOT NULL,
  `DS_IP` varchar(15) NOT NULL,
  `TP_REQUEST` varchar(20) NOT NULL,
  `CD_STATUS` int(3) NOT NULL,
  `DS_USER_AGENT` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;